-- require('gen').setup({
--   host = "localhost",
--   port = "11434",
--   -- model = "qwen2.5:14b",
--   model = "gemma3:27b-it-qat",
--   -- model = "mistral",
--   -- model = "gemma",
--   -- model = "llama2:7b",
--   -- model = "codellama:7b-instruct",
--   -- model = "codegemma:instruct",
--   -- show_model = true,
--   -- -- show_prompt = true,
--   -- display_mode = "split",
-- })
