#!/bin/bash

options=(
	style=round
	# style=square
	# width=1.5
	width=2.0
	order=above
	# hidpi=off
	hidpi=on
	# active_color=0xffe2e2e3
	active_color=0xffffffff
	# active_color="glow(0xffffffff)"
	# inactive_color=0xff414550
	inactive_color=0x00000000
)

borders "${options[@]}"
