#!/bin/bash

options=(
	style=round
	# style=square
	# width=1.5
	width=3.0
	order=above
	# hidpi=off
	hidpi=off
	# active_color=0xffe2e2e3
	#active_color=0xffffffff
	active_color="glow(0xffffffff)"
	ax_focus=on
	# active_color="glow(0xffff0000)"
	# active_color="0xffff0000"
	# inactive_color=0xff414550
	inactive_color=0x00000000
)

borders "${options[@]}"
